### ISSUE TITLE
Planets for black holes

### ISSUE THREAD

**Issue by RvCasteren** [mpigsley/sectors-without-number#106]
I thought it would be cool for black holes to be able to have planets as children too. Fictionally there is nothing stopping black holes to have planets so I thought that would be neat.

**Comment by mpigsley** [comment]
Yeah, all I can think of is Interstellar right now. The crazy time dilation could make for some fun story telling as well. Thanks for the suggestion! I'll try to find the probability of a planets orbiting a black hole and build that into the generator.
