### ISSUE TITLE
World Tag Internationalization

### ISSUE THREAD

**Issue by mpigsley** [mpigsley/sectors-without-number#113]

**Comment by JordanRR** [comment]
Ready to help!

**Comment by mpigsley** [comment]
Okay, so here's one world tag as it is currently:

```
  [worldTagKeys.alienRuins]: {
    key: worldTagKeys.alienRuins,
    name: 'Alien Ruins',
    description:
      'The world has significant alien ruins present. The locals may or may not permit others to investigate the ruins, and may make it difficult to remove any objects of value without substantial payment. Any surviving ruins with worthwhile salvage almost certainly have some defense or hazard to explain their unplundered state.',
    'misc.enemies': [
      'customs inspector',
      'worshipper of the ruins',
      'hidden alien survivor',
    ],
    'misc.friends': [
      'curious scholar',
      'avaricious local resident',
      'interstellar smuggler',
    ],
    'misc.complications': [
      'traps in the ruins',
      'remote location',
      'paranoid customs officials',
    ],
    'misc.things': [
      'precious alien artifacts',
      'objects left with the remains of a prior unsuccessful expedition',
      'untranslated alien texts',
      'untouched hidden ruins',
    ],
    'misc.places': [
      'undersea ruin',
      'orbital ruin',
      'perfectly preserved alien building',
      'alien mausoleum',
    ],
  },
```

This is what I'm thinking. The world tag entry in `world-tags.js` wold become:

```
  [worldTagKeys.alienRuins]: {
    key: worldTagKeys.alienRuins,
    enemies: 3,
    friends: 3,
    complications: 3,
    things: 4,
    places: 4,
  },
```

and the translations would look like:

```
"tags.alienRuins": "Alien Ruins",
"tags.alienRuins.description": The world has significant alien ruins present. The locals may or may not permit others to investigate the ruins, and may make it difficult to remove any objects of value without substantial payment. Any surviving ruins with worthwhile salvage almost certainly have some defense or hazard to explain their unplundered state.",
"tags.alienRuins.enemies.0": Customs inspector",
"tags.alienRuins.enemies.1": Worshipper of the ruins",
"tags.alienRuins.enemies.2": Hidden alien survivor",
"tags.alienRuins.friends.0": Curious scholar",
"tags.alienRuins.friends.1": Avaricious local resident",
"tags.alienRuins.friends.2": Interstellar smuggler",
"tags.alienRuins.complications.0": Traps in the ruins",
"tags.alienRuins.complications.1": Remote location",
"tags.alienRuins.complications.2": Paranoid customs officials",
"tags.alienRuins.things.0": Precious alien artifacts",
"tags.alienRuins.things.1": Objects left with the remains of a prior unsuccessful expedition",
"tags.alienRuins.things.2": Untranslated alien texts",
"tags.alienRuins.things.3": Untouched hidden ruins",
"tags.alienRuins.places.0": Undersea ruin",
"tags.alienRuins.places.1": Orbital ruin",
"tags.alienRuins.places.2": Perfectly preserved alien building",
"tags.alienRuins.places.3": Alien mausoleum",
```

I can derive the keys based on the given information contain in the world-tags entry. So the big thing to make sure is that in `tags.[world-tag-key]...`, `world-tag-key` matches the world tag key string. So in the case above `worldTagKeys.alienRuins` just equals `alienRuins`.

Let me know if you have any questions

**Comment by JordanRR** [comment]
Ok, so if I understand correctly, here is the task (keep in mind that I don't understand anything about code or github, so bear with me) :

1. I fork world-tags.js
2. For every tag, I delete what is already there, and what you plan instead (so "enemies: 3," and so on, depending on the tag). All of this must be made manually, so I copy and paste the new world entry, change the worldTagKeys.alienRuins to whatever the name of the tag, and make sure the numbers are right for enemies etc.

Then, for the translation :
1. Fork fr.json
2. Add a line for every entry of every tag like you made here, putting the french translation in. This also need to be done manually, so I copy and paste entries, change the name to whatever tag I'm working on, and add or delete entries id needed. For the translation itself, I copy and paste entries from the google doc. 

Am I understanding correctly?

**Comment by mpigsley** [comment]
All you'd need to do is fork `sectors-without-number` as a whole, clone your version of the repository to your computer, and then you can go in and edit anything you'd like without risking loosing any of the original data. That's the beauty of git and github. Here's some basic instructions but you can see a full listing [over here](http://kbroman.org/github_tutorial/pages/fork.html).

1. Fork sectors-without-number in Github
2. `git clone https://github.com/JordanRR/sectors-without-number.git`
3. `cd sectors-without-number`
4. `git checkout -b world-tag-translations` (create a branch)

Make any changes you'd like. You can commit your changes periodically by doing...

5. `git add .` (stage changes)
6. `git commit -m 'some description of your changes'`
7. `git push origin head` (push up to your github repository)

When you're done you'll open up a pull request. That's all covered in that article I linked above. I can chat with you on discord if you'd like `warpig#9483`. If you don't have a discord, shoot me an email (`mpigsley@gmail.com`) and we can setup something up.

**Comment by JordanRR** [comment]
Juat so you know, I'm doing the english translation right now, up to tags.misandryMisogyny. I'll continue to work on that later this week. Unless you prefer to have my partial work sooner, I'll make a pull request once it's done.

**Comment by mpigsley** [comment]
@JordanRR there's no rush so take your time 👍
