### ISSUE TITLE
Custom Hex Color Layers

### ISSUE THREAD

**Issue by mpigsley** [mpigsley/sectors-without-number#117]
My thought here is to have a faction toggle that will turn on/off the influence layer on the sector map.

What else could use custom hex colors? hmmm....

**Comment by meyar** [comment]
Threat level, "Intel level" (how much or what you know about a system), if you've visited it before.

**Comment by mpigsley** [comment]
I'm starting to think that maybe I need to open this up a bit and allow custom layers. Game masters could then create a "threat" or "intel" layer and then toggle between them in-game.

I could also see aliens having influence similar to factions, so having a way to link a given influence region to a specific faction or alien would need to be added.

**Comment by meyar** [comment]
Layers would be useful, aye.

**Comment by HiPoEGH** [comment]
I could imagine adding a color layer to a specific asset, and when that asset moves you can see how it would influence other systems.

**Comment by mpigsley** [comment]
@HiPoEGH you are referencing faction assets? Depending on how many factions you have, that could become _very_ busy in the interface.

**Comment by HiPoEGH** [comment]
Yes, I imagine it _could_ have the potential to get very cluttered. Then again people would be able to toggle the layer on/off if they wanted. They would also have to place a layer on every individual asset they want to see. Not all assets will have a color layer.
If Faction-A and Faction-B both have the same asset, in the same system, but I only place one layer on Asset-A, then I will only visually see Asset-A.
It's just a very low wishlist item. Being able to visualize any specific asset at any given time, to see an influence map of the varying Force, Cunning, or Wealth Assets.

From ItmeJP's and Adam Koebel's show with Far Verona, someone made a custom asset visual website.
https://farverona.742617000027.de/
I'm kind of imagening something like this, but maybe that's wishing a little much. This would only be colors on a single hex for now, I guess.

**Comment by mpigsley** [comment]
If you're just wanting to see what assets and types are at a particular location, what about just showing them in the hover tooltip instead. With color layers you'll still need to hover or click into the location to see what the colors represent. Especially if you have a lot of different assets scattered throughout your sector.

[Creating an automatic faction layer](https://github.com/mpigsley/sectors-without-number/issues/192) that allows you to see assets in the hovered tooltip is what I was hoping to do at some point.
