### ISSUE TITLE
Put "location" on all entities in overview

### ISSUE THREAD

**Issue by JordanRR** [mpigsley/sectors-without-number#123]
Right now, only systems have this information, but it would be useful for all entities.

**Comment by mpigsley** [comment]
Yeah, only systems and black holes do since they are the entity at that given hex. I really do like the idea of adding location to every other one though. Nice!

**Comment by mpigsley** [comment]
https://github.com/mpigsley/sectors-without-number/commit/4c42dde3be3efd2eebd020e3f999f83c89ec9677
