### ISSUE TITLE
Some expressions are not properly translated in french on the interface

### ISSUE THREAD

**Issue by JordanRR** [mpigsley/sectors-without-number#125]
The issue is not with the translation itself, because it's all right in some places. I'll list them here. 

- In the right panel, when you select a planet, the expression "Planet tags" read "Planète Marqueurs" in french. It should read "Marqueurs de planètes". 
- In the overview, the title of the list still reads "Entities", It should read "Entités". 

If I see some others, I'll add them. Thanks!

**Comment by mpigsley** [comment]
@JordanRR so for the `misc.entityTags` key should the french translation be `Marqueurs de {singular noun}`?

**Comment by JordanRR** [comment]
@mpigsley Yes, exactly! I changed it in the google doc. Thanks!

**Comment by mpigsley** [comment]
Awesome! Feel free to edit that google doc. I'll transfer over updated translations periodically.
