### ISSUE TITLE
Faction Generation

### ISSUE THREAD

**Issue by mpigsley** [mpigsley/sectors-without-number#13]
Should probably be a many to many relationship with entities.

Also, might need a way to toggle this feature in the configuration if people don't want that.

**Comment by mpigsley** [comment]
Allow multiple factions to lay claim to a system.

**Comment by mpigsley** [comment]
@Sifaus Yeah, I agree on all those points and you're proposal is very similar to what I was imagining. I was thinking about bundling things like Factions, Aliens, Adventures, etc. into their own tab under the overview and managing them from there. You'd be able to assign them to any entity that exists in your sector. Or not.

I know this is a greatly requested feature right now. If you want to have some sway in what gets worked on next, I take a vote between major projects on [Patreon](https://www.patreon.com/sectorswithoutnumber) for persons who are at the Interstellar Adventurer level.

**Comment by Sifaus** [comment]
Oh that's cool. Thanks for letting me know, I'll check it out.
