### ISSUE TITLE
JSON Export

### ISSUE THREAD

**Issue by Dr-Syn** [mpigsley/sectors-without-number#131]
Could it be possible to allow for export of the basic sector info in, say, JSON or XML? Was thinking of using, essentially, the table information that's presented in the PDF printout option to import into a GM dashboard.

[ This is an amazing tool, btw - thanks very much for building it! :-) ]

**Comment by mpigsley** [comment]
The entities within a sector are a massive hierarchy of data. Entities within entities. Would you want that data structure in the json/xml export? Or are you just wanting the lists of data with the columns that are shown in the overview?

**Comment by mpigsley** [comment]
```
{
  "sector": {
    "sector-id": {
      ...sector content
    },
    ...
  },
  "system": {
    "system-id": {
      "parentType": "sector",
      "parent": "sector-id",
      ...other system content
    },
    ...
  },
}
```

Then to find the parent of any given entity you'd just go `export[entity.parentType][entity.parent]`.

All this to say... I have exactly this data in the store already so this would be an easy update.

**Comment by Dr-Syn** [comment]
Oh fantastic - thank you :-) :+1:
