### ISSUE TITLE
Additional Generation Options

### ISSUE THREAD

**Issue by Theagle43** [mpigsley/sectors-without-number#134]
It would be nice to have a finer level of customization over the custom sectors, such as:
- Only allow one planet per system
- Every system has at least one planet
- Avoid duplicate world tags (multiple worlds having the same tag)
- Avoid duplicate world/system names (multiple worlds or systems having the same name)
Etc.

**Comment by mpigsley** [comment]
Awesome! I'm going to create tickets for each one of these options you have listed 👍
