### ISSUE TITLE
Wrong weighting in planet generation

### ISSUE THREAD

**Issue by AstroT** [mpigsley/sectors-without-number#165]
When assigning attributes to planets (TL, Atmo, Temp, etc) the weightings don't take into account the distribution that comes from rolling 2d6 and then looking up the table. As such 'rare' results are far more common and 'typical' results are fare rare than they should be

For example lines 45-48 of "src/utils/entity-generators/planet-generator.js" are:

        techLevel: `TL${chance.weighted(
          ['0', '1', '2', '3', '4', '4+', '5'],
          [1, 1, 2, 2, 3, 1, 1],
        )}`,

But instead should be weighted as such:

        techLevel: `TL${chance.weighted(
          ['0', '1', '2', '3', '4', '4+', '5'],
          [1, 2, 7, 7, 16, 2, 1],
        )}`,

Hope this makes sense!

**Comment by mpigsley** [comment]
You're absolutely right. I'll get this patched very soon. Thank you!

**Comment by mpigsley** [comment]
Fixed in `v5.4.3`.
