### ISSUE TITLE
Allow multiple descriptions for an entity

### ISSUE THREAD

**Issue by jeremyf** [mpigsley/sectors-without-number#166]
As a GM, I want to have a set of descriptions that I can keep private and a set of descriptions that I can make public, so I can manage what information my players can see about a give system.

**Comment by mpigsley** [comment]
Hey @jeremyf, you can create notes on any entity that allow you to toggle the visibility to your players. You can have as many notes as you'd like and they support [full markdown](https://daringfireball.net/projects/markdown/syntax) so you can add lists, images, tables, etc.

The description field on an entity is a little blurb for you and your players, while notes are designed for everything else.
