### ISSUE TITLE
Mobile View

### ISSUE THREAD

**Issue by mpigsley** [mpigsley/sectors-without-number#167]
Give some love to the mobile view. This could mean removing the sector entirely for now and only showing the entity navigation or it could mean a way to switch between the sidebar and sector.

**Comment by mpigsley** [comment]
The sector view is sized more appropriately at smaller viewports since #171

**Comment by Atreusion** [comment]
Out of curiosity, is the sector view supposed to be clickable on mobile? Or am I missing something?

Using Safari on iPad 9.7", iOS 12.1.1.

**Comment by mpigsley** [comment]
It's not optimized for mobile or tablet for that matter. Haven't really even done much testing so it's entirely possible that you can't click around.
