### ISSUE TITLE
Hide notes from players

### ISSUE THREAD

**Issue by humburg** [mpigsley/sectors-without-number#205]
I'm really enjoying building and exploring sectors with this. One feature that I would find very useful would be the ability to hide the notes for an entity without hiding it completely. That way I could add notes that aren't immediately visible to the players, even if they can see the planet/system/etc. It might be even better to have a public description and a private notes section.

**Comment by mpigsley** [comment]
Howdy! There is a notes section already and you can control if each note is shown to players. Here's a gif of how to do that.

![hidden-note](https://user-images.githubusercontent.com/3017491/48779421-32bbf700-ec9d-11e8-9f19-e87892cad169.gif)

This can be done on any entity within your sector 👍.

**Comment by humburg** [comment]
Somehow I completely missed that and saw only the Description text box. This works great, thanks!

**Comment by mpigsley** [comment]
No problem! Also, you can use markdown in those notes so you can embed images, tables, headers, etc. etc.

**Comment by humburg** [comment]
That is awesome! I had no idea there was Markdown support.
