### ISSUE TITLE
Routes through only empty hexes are marked as hidden

### ISSUE THREAD

**Issue by eScribMac** [mpigsley/sectors-without-number#206]
![image](https://user-images.githubusercontent.com/4968747/50745909-9de46d00-11fa-11e9-9cb2-9427cf05966b.png)

**Comment by eScribMac** [comment]
I was trying to use it to represent the location of the party, they might start a session in empty space. Is there a better way to represent the party's current location?

**Comment by mpigsley** [comment]
I would use a layer to do that. [Here's some more information](https://medium.com/@mpigsley/sectors-without-number-custom-hex-layers-97e5f423b973).
