### ISSUE TITLE
Right Click, Context Menu

### ISSUE THREAD

**Issue by HiPoEGH** [mpigsley/sectors-without-number#209]
When in Edit Mode, allow users to quickly add/generate entities on specific EMPTY hex cells by adding a context menu via right click. 
Something like:
RC > Add System
RC > Add Black Hole

**Comment by mpigsley** [comment]
@HiPoEGH there is a little known feature of SectWN that allows you to click and hold on an empty hex in edit mode to pull up a dialog to add a system/black-hole and populate children.

**Comment by HiPoEGH** [comment]
Yeah just noticed that today.
It doesn't seem very intuitive but I guess it's functional.

Maybe perhaps have an 'edit mode' that puts a quickbar on the top? Allowing for people to quickly do things like this on the selected Hex. I dont know really but I'm just brainstorming ideas.
