### ISSUE TITLE
Suggestion: Give users the ability to give attributes and planetary features to moons.

### ISSUE THREAD

**Issue by MemedHams** [mpigsley/sectors-without-number#225]
Moons attached to planets could benefit from an attribute and planetary feature bar similar to that of their parent spheres. Though the description bar can serve to hold this information for now, these alterations could benefit system flexibility, allowing for easier creation of Ionian colonies in the orbit of gas giants and wild, ruin-addled jungle moons.

**Comment by mpigsley** [comment]
@MemedHams this is a really good point! The problem is that there are no official attributes for moons so it'll be a blank dropdown but you'll be able to type in your own.
