### ISSUE TITLE
Add sector import from json file

### ISSUE THREAD

**Issue by morops** [mpigsley/sectors-without-number#257]
We already have the ability to export json. Could we also add an interface to import a sector from an uploaded json file? This might make it easier for users to apply blanket changes that don't exist in the UI.

**Comment by mpigsley** [comment]
Howdy! I have a ticket open for [JSON Import](https://github.com/mpigsley/sectors-without-number/issues/179) already. You are definitely not the first person to request this. I'll raise it up in priority.
