### ISSUE TITLE
Player & GM Views

### ISSUE THREAD

**Issue by mpigsley** [mpigsley/sectors-without-number#35]
Basically just a way to hide information for players with a shareable link. This will need to be wired up after #34

**Comment by vinbreauX** [comment]
This feature would help me immensely. Any update or ETA you can provide for this?

**Comment by mpigsley** [comment]
Working on adding additional points of interest then this is the next feature after that. I'd say probably a month or so. [I posted a mockup of what the new hide feature will look like over here](https://github.com/mpigsley/sectors-without-number/issues/46#issuecomment-345076203).
