### ISSUE TITLE
Custom World Tags

### ISSUE THREAD

**Issue by mpigsley** [mpigsley/sectors-without-number#65]
This is the start of what I view as a larger project. I can see a whole other part of the website where you can create and edit custom attributes, tags, and other content that can augment your generator.

World tags would be an easy first step into this.

**Comment by meyar** [comment]
Really looking forward to this feature, thanks for the hard work. Is there a rough guesstimate if when it might be implemented?

**Comment by mpigsley** [comment]
@meyar I am currently working on a rewrite to set me up for some of these larger changes down the road. I'm hoping to get that out mid to late January. From there I'd like to tackle hiding content from players, adding additional points of interest into the generator, and then tackling custom content. 
It'll end up being completed a few months into 2018 if everything goes as planned.

**Comment by meyar** [comment]
Better than I'd hoped. Appreciate the work!

**Comment by Zeikko** [comment]
Have you finished the rewrite you mentioned earlier? Is this feature something that i could possibly help with?

**Comment by mpigsley** [comment]
@Zeikko Yeah, the major rewrite is already done. Yeah, the custom tags would be fairly easy. The biggest thing would be the design. It'll live outside of the game view so you can apply a user's custom tags to any game the user owns. If you have a discord, we can chat about it more in depth some time. My username is `warpig#9483`.

**Comment by Zeikko** [comment]
I'll be in touch!

**Comment by mpigsley** [comment]
As a first pass on this, allowing custom tags to just be written in on a planet could be doable. They wouldn't be saved for the generator though.
