### ISSUE TITLE
Limit number of local/server saved sectors

### ISSUE THREAD

**Issue by mpigsley** [mpigsley/sectors-without-number#72]
The biggest reason here being that storage isn't free. I don't think anyone would need more than three saved sectors anyway.

**Comment by Karlinator** [comment]
I vote for overestimating the number of sectors anyone would reasonably need. If I'm not mistaken, this limit is intended to not interfere with normal use in any way, but stop people's ability to use a bunch of storage for the hell of it. If that is correct, I think a number closer to 5 or 10 would be better, as it won't change data usage of the average user, it would accommodate crazy GM's who run 4 games or something (as well as those who just have several sectors laying in wait), and would still stop abuse of the infinite storage.

**Comment by mpigsley** [comment]
That's fair @Karlinator. I can bump it up to 5 sectors.
