### ISSUE TITLE
login error

### ISSUE THREAD

**Issue by bluetyson** [mpigsley/sectors-without-number#82]
When I signed up...either site....it said 'there has been an error' after doing so, even though got the email with no problem.

**Comment by mpigsley** [comment]
@bluetyson did you use a login provider facebook/google or email/password?

**Comment by bluetyson** [comment]
Email/password and Windows 10 Edge browser

**Comment by mpigsley** [comment]
Wasn't able to reproduce the error. I'll leave this open for the time being. If I don't hear of others having problems then I'll close it at a later date.

**Comment by bluetyson** [comment]
I'll see what happens on a different machine

**Comment by mpigsley** [comment]
Closing since I haven't heard anything more from anyone.
