### ISSUE TITLE
Improve SVG Generation & Rendering to Allow Larger Sectors

### ISSUE THREAD

**Issue by meyar** [mpigsley/sectors-without-number#88]
I have a sneaking suspicion this may be intentional and not a bug, but just tossing it up just in case. I've previously generated a 20x20 sector, but going back to make a new sector, it's currently limited to 15x15. My old 20x20 is still accessible.

**Comment by mpigsley** [comment]
Hey @meyar, yeah you are correct I set it back to 15x15 max. I might bring back that 20x20 at some point but for now you are lucky you generated before my limit :)

**Comment by meyar** [comment]
I may well be an edge case. I'm the crazy guy who had 4 separate sectors generated for a game I ran. The 20x20 limit was nice in that it had the same amount of hexes plus an extra 80 or so. I hope it comes back some day but I won't exactly hold it against you if it doesn't make a return.

**Comment by mpigsley** [comment]
@meyar it was more for performance reasons than anything. It was a bit laggy and slow to respond. I'll change this issue into a general performance issue so that we can potentially bring that 20x20 grid back.

**Comment by meyar** [comment]
I'd love to see it work again but I'm not gonna lose sleep over it if it can't make a return for performance reasons. Appreciate the consideration regardless of outcome, thanks!

**Comment by mpigsley** [comment]
Another thought I had was to render the background hexes on a canvas instead of rendering individual svg polygons for them. Then position the sector SVG on top of the canvas so we can still use the react events from the SVG polygon elements.
