### ISSUE TITLE
System children number out of hex bounds on printout

### ISSUE THREAD

**Issue by iamrpgdm** [mpigsley/sectors-without-number#92]
The printout shows the system children number shifted up outside the hex bounds. It occurs with Chrome, Firefox, Opera and Edge that I tested.
<img width="487" alt="sectorprint1" src="https://user-images.githubusercontent.com/33824743/36085699-e5da6070-0f84-11e8-9976-5313ada6a51f.png">

**Comment by meyar** [comment]
Can reproduce. The print out also seems to not print out newer changes like space stations but I may be wrong

**Comment by mpigsley** [comment]
Yup, I can reproduce it as well. Thanks for the issue!

**Comment by meyar** [comment]
To clarify: It prints out the blackholes (same color as the planets but not sure that's an issue as they're labeled with their obvious names), just doesn't list stations, research stations, refuel stops and ruins in the system details of the printout.

**Comment by mpigsley** [comment]
@meyar I've changed it so that planets and black holes can be differentiated.

<img width="499" alt="screen shot 2018-02-12 at 7 57 25 am" src="https://user-images.githubusercontent.com/3017491/36100021-6243c828-0fca-11e8-811e-cdec093b7428.png">
